import { Inter } from "next/font/google";
import "./globals.css";
import RefContextProvider from "./Context/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Only1 Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RefContextProvider>{children}</RefContextProvider>
      </body>
    </html>
  );
}
